# Data set 1: 1000 Genome

The data was downloaded from 1000 Genome dataset
here is the link to the data: 
    https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz

# Step 1 Inspect file

In [ ]:
!zless /home/jovyan/work/Jupyter_docker/SNP_interview/input/1000Genome/1000genome_test.vcf.gz

## 1. gzipped Variant Call Format file => tsv

In [ ]:
## 1000 Genome
#import gzip
#import pandas as pd

## Path to your file
#vcf_path = "/home/jovyan/work/Jupyter_docker/SNP_interview/input/1000Genome/1000genome_test.vcf.gz"

## Find header line
#with gzip.open(vcf_path, 'rt') as f:
#    for line in f:
#        if line.startswith('#CHROM'):
#            header = line.strip().split('\t')
#            break

## Read file into pandas
#df = pd.read_csv(
#    vcf_path,
#    compression='gzip',
#    comment='#',
#    sep='\t',
#    names=header
#)

#print(df.head())
#print(f"\nTotal variants: {len(df):,}")

##df.to_csv("variants_1000G.tsv", sep="\t", index=False)

In [1]:
import pandas as pd
#vcf_path = "/home/jovyan/work/Jupyter_docker/SNP_interview/input/clinvar_test.tsv"
vcf_path = "/home/jovyan/work/Jupyter_docker/SNP_interview/input/1000Genome/1000genome_test.tsv"

df = pd.read_csv(vcf_path, sep='\t')
print(df.head())
print(df.shape)

   CHROM    POS ID REF ALT  QUAL FILTER  \
0      1  10177  .   A  AC   100   PASS
1      1  10235  .   T  TA   100   PASS
2      1  10352  .   T  TA   100   PASS
3      1  10505  .   A   T   100   PASS
4      1  10506  .   C   G   100   PASS

                                                INFO FORMAT HG00096  ...  \
0  AC=2130;AF=0.425319;AN=5008;NS=2504;DP=103152;...     GT     1|0  ...
1  AC=6;AF=0.00119808;AN=5008;NS=2504;DP=78015;EA...     GT     0|0  ...
2  AC=2191;AF=0.4375;AN=5008;NS=2504;DP=88915;EAS...     GT     1|0  ...
3  AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9632;EA...     GT     0|0  ...
4  AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9676;EA...     GT     0|0  ...

  NA21128 NA21129 NA21130 NA21133 NA21135 NA21137 NA21141 NA21142 NA21143  \
0     0|0     0|1     0|0     1|0     1|0     1|0     1|0     0|1     0|0
1     0|0     0|0     0|0     0|0     0|0     0|0     1|0     0|0     0|0
2     0|0     0|1     1|0     0|1     1|0     0|1     1|0     0|0     0|1
3     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0
4     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0     0|0

  NA21144
0     0|1
1     0|0
2     0|1
3     0|0
4     0|0

[5 rows x 2513 columns]
(500, 2513)

In [2]:
df.head()

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,FORMAT,HG00096,...,NA21128,NA21129,NA21130,NA21133,NA21135,NA21137,NA21141,NA21142,NA21143,NA21144
0,1,10177,.,A,AC,100,PASS,AC=2130;AF=0.425319;AN=5008;NS=2504;DP=103152;...,GT,1|0,...,0|0,0|1,0|0,1|0,1|0,1|0,1|0,0|1,0|0,0|1
1,1,10235,.,T,TA,100,PASS,AC=6;AF=0.00119808;AN=5008;NS=2504;DP=78015;EA...,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,1|0,0|0,0|0,0|0
2,1,10352,.,T,TA,100,PASS,AC=2191;AF=0.4375;AN=5008;NS=2504;DP=88915;EAS...,GT,1|0,...,0|0,0|1,1|0,0|1,1|0,0|1,1|0,0|0,0|1,0|1
3,1,10505,.,A,T,100,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9632;EA...,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0
4,1,10506,.,C,G,100,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9676;EA...,GT,0|0,...,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0,0|0

In [ ]:
#df.columns.tolist() #ดุชื่อ column

## 2) เตรียมคอลัมน์พื้นฐาน

In [3]:
import pandas as pd
import numpy as np
import re

In [4]:
# select column
df = df[['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO']]

df.head()

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO
0,1,10177,.,A,AC,100,PASS,AC=2130;AF=0.425319;AN=5008;NS=2504;DP=103152;...
1,1,10235,.,T,TA,100,PASS,AC=6;AF=0.00119808;AN=5008;NS=2504;DP=78015;EA...
2,1,10352,.,T,TA,100,PASS,AC=2191;AF=0.4375;AN=5008;NS=2504;DP=88915;EAS...
3,1,10505,.,A,T,100,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9632;EA...
4,1,10506,.,C,G,100,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9676;EA...

## 3) Sanity check

In [5]:
df['POS'].unique()[:10]

array([10177, 10235, 10352, 10505, 10506, 10511, 10539, 10542, 10579,
       10616])

In [6]:
# observe data
unique_values = df.apply(pd.Series.unique)
print(unique_values)

CHROM                                                   [1]
POS       [10177, 10235, 10352, 10505, 10506, 10511, 105...
ID                                                      [.]
REF       [A, T, C, G, CCGCCGTTGCAAAGGCGCGCCG, CCT, CA, ...
ALT       [AC, TA, T, G, A, C, G,T, GC, GT, TTTTC, AAC, ...
QUAL                                                  [100]
FILTER                                               [PASS]
INFO      [AC=2130;AF=0.425319;AN=5008;NS=2504;DP=103152...
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CHROM   500 non-null    int64
 1   POS     500 non-null    int64
 2   ID      500 non-null    object
 3   REF     500 non-null    object
 4   ALT     500 non-null    object
 5   QUAL    500 non-null    int64
 6   FILTER  500 non-null    object
 7   INFO    500 non-null    object
dtypes: int64(3), object(5)
memory usage: 31.4+ KB

# Step 2 Clear and prep data

## 1. Keep only SNPs (and split multi-allelic sites)

In [8]:
import pandas as pd

# 5.0 Ensure canonical columns exist
base_cols = ['CHROM','POS','ID','REF','ALT','QUAL','FILTER','INFO']
missing = [c for c in base_cols if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}")

# 5.1 Split multi-allelic records (ALT = 'A,C') into separate rows
df = df.assign(ALT=df['ALT'].str.split(',')).explode('ALT')

# 5.2 Enforce SNPs only (single-base REF/ALT; drop anything else)
is_snp = (df['REF'].str.len() == 1) & (df['ALT'].str.len() == 1)
df = df[is_snp].copy()

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 472 entries, 3 to 499
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CHROM   472 non-null    int64
 1   POS     472 non-null    int64
 2   ID      472 non-null    object
 3   REF     472 non-null    object
 4   ALT     472 non-null    object
 5   QUAL    472 non-null    int64
 6   FILTER  472 non-null    object
 7   INFO    472 non-null    object
dtypes: int64(3), object(5)
memory usage: 33.2+ KB

In [9]:
# 5.3 Basic de-dup + sorting
df['POS'] = pd.to_numeric(df['POS'], errors='coerce')
df = df.dropna(subset=['POS'])
df = df.drop_duplicates(subset=['CHROM','POS','REF','ALT'])
df = df.sort_values(['CHROM','POS'])

df.info()

print(f"✅ After SNP-only & split: {len(df):,} rows")
df[['CHROM','POS','REF','ALT','QUAL','FILTER']].head()

<class 'pandas.core.frame.DataFrame'>
Index: 472 entries, 3 to 499
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CHROM   472 non-null    int64
 1   POS     472 non-null    int64
 2   ID      472 non-null    object
 3   REF     472 non-null    object
 4   ALT     472 non-null    object
 5   QUAL    472 non-null    int64
 6   FILTER  472 non-null    object
 7   INFO    472 non-null    object
dtypes: int64(3), object(5)
memory usage: 33.2+ KB
✅ After SNP-only & split: 472 rows

   CHROM    POS REF ALT  QUAL FILTER
3      1  10505   A   T   100   PASS
4      1  10506   C   G   100   PASS
5      1  10511   G   A   100   PASS
6      1  10539   C   A   100   PASS
7      1  10542   C   T   100   PASS

## 2. Basic QC (FILTER & QUAL)

In [10]:
# Accept PASS or '.' (some callers leave '.')
pass_mask = df['FILTER'].isin(['PASS','.'])
df = df[pass_mask].copy()

# Optional QUAL ≥ 30 (only if present/meaningful for your caller)
df['QUAL_num'] = pd.to_numeric(df['QUAL'], errors='coerce')
df = df[(df['QUAL'].eq('.')) | (df['QUAL_num'] >= 30)].drop(columns=['QUAL_num'])

print(f"✅ After FILTER/QUAL: {len(df):,} rows")
df.info()

✅ After FILTER/QUAL: 472 rows
<class 'pandas.core.frame.DataFrame'>
Index: 472 entries, 3 to 499
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CHROM   472 non-null    int64
 1   POS     472 non-null    int64
 2   ID      472 non-null    object
 3   REF     472 non-null    object
 4   ALT     472 non-null    object
 5   QUAL    472 non-null    int64
 6   FILTER  472 non-null    object
 7   INFO    472 non-null    object
dtypes: int64(3), object(5)
memory usage: 33.2+ KB

## 3. Parse INFO column → Python dictionary → DataFrame columns

In [11]:
df['INFO']

3      AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9632;EA...
4      AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9676;EA...
5      AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9869;EA...
6      AC=3;AF=0.000599042;AN=5008;NS=2504;DP=9203;EA...
7      AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9007;EA...
                             ...
495    AC=24;AF=0.00479233;AN=5008;NS=2504;DP=23495;E...
496    AC=1;AF=0.000199681;AN=5008;NS=2504;DP=19024;E...
497    AC=280;AF=0.0559105;AN=5008;NS=2504;DP=20195;E...
498    AC=170;AF=0.0339457;AN=5008;NS=2504;DP=19844;E...
499    AC=2;AF=0.000399361;AN=5008;NS=2504;DP=19865;E...
Name: INFO, Length: 472, dtype: object

In [12]:
print(df['INFO'].iloc[0].split(';'))

['AC=1', 'AF=0.000199681', 'AN=5008', 'NS=2504', 'DP=9632', 'EAS_AF=0', 'AMR_AF=0', 'AFR_AF=0.0008', 'EUR_AF=0', 'SAS_AF=0', 'AA=.|||', 'VT=SNP']

In [13]:
import pandas as pd

# --- Parse each INFO field into a dict ---
def parse_info(s):
    info_dict = {}
    if pd.isna(s):
        return info_dict
    for kv in str(s).split(';'):
        if '=' in kv:
            k, v = kv.split('=', 1)
            info_dict[k] = v
        elif kv:  # flag (no value)
            info_dict[k] = True
    return info_dict

# Convert INFO strings to dict objects
df['INFO_dict'] = df['INFO'].map(parse_info)

# Inspect one
print(df['INFO_dict'].iloc[0])

{'AC': '1', 'AF': '0.000199681', 'AN': '5008', 'NS': '2504', 'DP': '9632', 'EAS_AF': '0', 'AMR_AF': '0', 'AFR_AF': '0.0008', 'EUR_AF': '0', 'SAS_AF': '0', 'AA': '.|||', 'VT': 'SNP'}

In [14]:
df['INFO_dict']

3      {'AC': '1', 'AF': '0.000199681', 'AN': '5008',...
4      {'AC': '1', 'AF': '0.000199681', 'AN': '5008',...
5      {'AC': '1', 'AF': '0.000199681', 'AN': '5008',...
6      {'AC': '3', 'AF': '0.000599042', 'AN': '5008',...
7      {'AC': '1', 'AF': '0.000199681', 'AN': '5008',...
                             ...
495    {'AC': '24', 'AF': '0.00479233', 'AN': '5008',...
496    {'AC': '1', 'AF': '0.000199681', 'AN': '5008',...
497    {'AC': '280', 'AF': '0.0559105', 'AN': '5008',...
498    {'AC': '170', 'AF': '0.0339457', 'AN': '5008',...
499    {'AC': '2', 'AF': '0.000399361', 'AN': '5008',...
Name: INFO_dict, Length: 472, dtype: object

## 4. Expand INFO dict → individual columns (Optional)

In [15]:
info_df = df['INFO_dict'].apply(pd.Series)
df = pd.concat([df, info_df], axis=1)
df.head()

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,INFO,INFO_dict,AC,...,AN,NS,DP,EAS_AF,AMR_AF,AFR_AF,EUR_AF,SAS_AF,AA,VT
3,1,10505,.,A,T,100,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9632;EA...,"{'AC': '1', 'AF': '0.000199681', 'AN': '5008',...",1,...,5008,2504,9632,0,0,0.0008,0,0,.|||,SNP
4,1,10506,.,C,G,100,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9676;EA...,"{'AC': '1', 'AF': '0.000199681', 'AN': '5008',...",1,...,5008,2504,9676,0,0,0.0008,0,0,.|||,SNP
5,1,10511,.,G,A,100,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9869;EA...,"{'AC': '1', 'AF': '0.000199681', 'AN': '5008',...",1,...,5008,2504,9869,0,0.0014,0,0,0,.|||,SNP
6,1,10539,.,C,A,100,PASS,AC=3;AF=0.000599042;AN=5008;NS=2504;DP=9203;EA...,"{'AC': '3', 'AF': '0.000599042', 'AN': '5008',...",3,...,5008,2504,9203,0,0.0014,0,0.001,0.001,.|||,SNP
7,1,10542,.,C,T,100,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9007;EA...,"{'AC': '1', 'AF': '0.000199681', 'AN': '5008',...",1,...,5008,2504,9007,0.001,0,0,0,0,.|||,SNP

# Step 3: FILTERING ========

## 1) Coerce numerics & derive handy metrics

In [16]:
num_cols = [
    'AC','AN','AF','NS','DP','MQ','QD','VQSLOD',
    'EAS_AF','EUR_AF','AFR_AF','AMR_AF','SAS_AF'
]
for c in num_cols:
    if c in df.columns:
        df[c] = pd.to_numeric(df[c], errors='coerce')

# If AF missing, derive it from AC/AN when possible
#if 'AF' not in df.columns or df['AF'].isna().all():
#    if {'AC','AN'}.issubset(df.columns):
#        df['AF'] = df['AC'] / df['AN']

# Minor allele frequency (helps symmetric filtering)
df['MAF'] = df['AF'].where(df['AF'] <= 0.5, 1 - df['AF'])

In [17]:
df.columns

Index(['CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO',
       'INFO_dict', 'AC', 'AF', 'AN', 'NS', 'DP', 'EAS_AF', 'AMR_AF', 'AFR_AF',
       'EUR_AF', 'SAS_AF', 'AA', 'VT', 'MAF'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 472 entries, 3 to 499
Data columns (total 22 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CHROM      472 non-null    int64
 1   POS        472 non-null    int64
 2   ID         472 non-null    object
 3   REF        472 non-null    object
 4   ALT        472 non-null    object
 5   QUAL       472 non-null    int64
 6   FILTER     472 non-null    object
 7   INFO       472 non-null    object
 8   INFO_dict  472 non-null    object
 9   AC         470 non-null    float64
 10  AF         470 non-null    float64
 11  AN         472 non-null    int64
 12  NS         472 non-null    int64
 13  DP         472 non-null    int64
 14  EAS_AF     470 non-null    float64
 15  AMR_AF     470 non-null    float64
 16  AFR_AF     470 non-null    float64
 17  EUR_AF     470 non-null    float64
 18  SAS_AF     470 non-null    float64
 19  AA         472 non-null    object
 20  VT         472 non-null    object
 21  MAF        470 non-null    float64
dtypes: float64(8), int64(6), object(8)
memory usage: 84.8+ KB

## 2) Quick sanity checks (catch bugs fast)

In [19]:
# Ensure we’re still on SNPs after explode
assert (df['REF'].str.len()==1).all() and (df['ALT'].str.len()==1).all()

# If present, keep VT=SNP (some files include VT)
if 'VT' in df.columns:
    df = df[df['VT'].eq('SNP')].copy()

# FILTER field: keep PASS or '.' (some callers use '.')
if 'FILTER' in df.columns:
    df = df[df['FILTER'].isin(['PASS','.'])].copy()

print("Rows after basic checks:", len(df))

Rows after basic checks: 425

## 3) Define thresholds (interview-friendly defaults)

These are typical, reasonable defaults that you can explain:

- Rarity: global MAF < 1% (or 0.5% if you want stricter)

- Across populations: make sure it’s not common in any subpopulation

- Quality: MQ ≥ 40, QD ≥ 2, VQSLOD > 0 (when present)

- Depth: total site depth not too low (avoid ultra-low coverage calls). For 1000G sites, use a soft floor (e.g., DP ≥ 100)

- Completeness: NS close to cohort size (avoid sites genotyped in very few samples)

In [20]:
# ---- Rarity thresholds ----
GLOBAL_MAF_MAX = 0.01   # keep variants with MAF < 1% globally
POP_MAF_MAX    = 0.01   # and < 1% in every subpopulation present

# ---- Quality thresholds (used only if present in INFO) ----
MQ_MIN, QD_MIN, VQSLOD_MIN = 40, 2, 0
DP_MIN, NS_MIN = 100, 1500  # site-level depth and #samples with data

# Keys for population AFs that may exist in your INFO
POP_KEYS = ['EAS_AF','EUR_AF','AFR_AF','AMR_AF','SAS_AF']

## 4) Helpers to read from INFO_dict safely

In [21]:
import pandas as pd

def fget(d, key, cast=float, default=None):
    """Safe getter from INFO_dict with casting and comma-list handling."""
    if not isinstance(d, dict): return default
    v = d.get(key, default)
    if v is None: return default
    if isinstance(v, str) and ',' in v:
        v = v.split(',', 1)[0]
    try:
        return cast(v) if cast else v
    except Exception:
        return default

## 5) Build the single filtering function

In [22]:
def pass_info_filter(d):
    # 1) SNP-only if VT is present
    vt = fget(d, 'VT', str, '')
    if vt and vt != 'SNP':
        return False

    # 2) Global rarity (use AF or derive from AC/AN)
    af = fget(d, 'AF', float, None)
    if af is None:
        ac, an = fget(d, 'AC', float, None), fget(d, 'AN', float, None)
        af = (ac / an) if (ac is not None and an not in (None, 0)) else None
    maf = (af if (af is not None and af <= 0.5) else (1 - af) if af is not None else None)
    if maf is not None and maf >= GLOBAL_MAF_MAX:
        return False  # common globally

    # 3) Rare in every subpopulation that exists in this record
    for k in POP_KEYS:
        v = fget(d, k, float, None)
        if v is not None and v >= POP_MAF_MAX:
            return False

    # 4) Quality (skip check if field is absent)
    dp  = fget(d, 'DP', float, None)
    ns  = fget(d, 'NS', float, None)
    mq  = fget(d, 'MQ', float, None)
    qd  = fget(d, 'QD', float, None)
    vqs = fget(d, 'VQSLOD', float, None)

    if dp  is not None and dp  < DP_MIN:        return False
    if ns  is not None and ns  < NS_MIN:        return False
    if mq  is not None and mq  < MQ_MIN:        return False
    if qd  is not None and qd  < QD_MIN:        return False
    if vqs is not None and vqs <= VQSLOD_MIN:   return False

    return True

## 6) Apply the filter and inspect results

In [23]:
# Respect site FILTER too (if present at top level, not inside INFO)
if 'FILTER' in df.columns:
    df = df[df['FILTER'].isin(['PASS','.'])].copy()

mask = df['INFO_dict'].map(pass_info_filter)
candidates = df.loc[mask, ['CHROM','POS','ID','REF','ALT','FILTER','INFO', 'MAF']].copy()

# (Optional) surface a few INFO values for quick viewing
candidates['AF']      = df.loc[mask, 'INFO_dict'].map(lambda d: fget(d, 'AF', float, None))
candidates['DP']      = df.loc[mask, 'INFO_dict'].map(lambda d: fget(d, 'DP', float, None))
candidates['NS']      = df.loc[mask, 'INFO_dict'].map(lambda d: fget(d, 'NS', float, None))
for k in POP_KEYS:
    candidates[k] = df.loc[mask, 'INFO_dict'].map(lambda d, k=k: fget(d, k, float, None))

print(f"✅ Candidates after INFO-only filters: {len(candidates):,}")
candidates.head(10)

✅ Candidates after INFO-only filters: 336

,CHROM,POS,ID,REF,ALT,FILTER,INFO,MAF,AF,DP,NS,EAS_AF,EUR_AF,AFR_AF,AMR_AF,SAS_AF
3,1,10505,.,A,T,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9632;EA...,0.000200,0.000200,9632.0,2504.0,0.000,0.000,0.0008,0.0000,0.000
4,1,10506,.,C,G,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9676;EA...,0.000200,0.000200,9676.0,2504.0,0.000,0.000,0.0008,0.0000,0.000
5,1,10511,.,G,A,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9869;EA...,0.000200,0.000200,9869.0,2504.0,0.000,0.000,0.0000,0.0014,0.000
6,1,10539,.,C,A,PASS,AC=3;AF=0.000599042;AN=5008;NS=2504;DP=9203;EA...,0.000599,0.000599,9203.0,2504.0,0.000,0.001,0.0000,0.0014,0.001
7,1,10542,.,C,T,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=9007;EA...,0.000200,0.000200,9007.0,2504.0,0.001,0.000,0.0000,0.0000,0.000
8,1,10579,.,C,A,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=5502;EA...,0.000200,0.000200,5502.0,2504.0,0.000,0.000,0.0008,0.0000,0.000
14,1,13011,.,T,G,PASS,AC=3;AF=0.000599042;AN=5008;NS=2504;DP=35822;E...,0.000599,0.000599,35822.0,2504.0,0.000,0.000,0.0023,0.0000,0.000
18,1,13156,.,G,C,PASS,AC=1;AF=0.000199681;AN=5008;NS=2504;DP=28002;E...,0.000200,0.000200,28002.0,2504.0,0.000,0.000,0.0000,0.0000,0.001
19,1,13259,.,G,A,PASS,AC=2;AF=0.000399361;AN=5008;NS=2504;DP=31820;E...,0.000399,0.000399,31820.0,2504.0,0.000,0.000,0.0015,0.0000,0.000
21,1,13284,.,G,A,PASS,AC=7;AF=0.00139776;AN=5008;NS=2504;DP=26384;EA...,0.001398,0.001398,26384.0,2504.0,0.001,0.000,0.0045,0.0000,0.000

## 7) Save a tidy TSV

In [24]:
candidates.sort_values(['CHROM','POS']).to_csv(
    "candidates_from_INFO_dict.tsv",
    sep='\t', index=False
)
print("Wrote: candidates_from_INFO_dict.tsv")

Wrote: candidates_from_INFO_dict.tsv

# Step 4 Functional Annotation — “What does each SNP do?”

In [25]:
!pip install pyensembl
!python -m pyensembl install --release 105 --species homo_sapiens

Collecting pyensembl
  Using cached pyensembl-2.3.13-py3-none-any.whl.metadata (9.4 kB)
Collecting typechecks<1.0.0,>=0.0.2 (from pyensembl)
  Using cached typechecks-0.1.0-py3-none-any.whl
Collecting datacache<2.0.0,>=1.4.0 (from pyensembl)
  Using cached datacache-1.4.1-py3-none-any.whl.metadata (1.9 kB)
Collecting memoized-property>=1.0.2 (from pyensembl)
  Using cached memoized_property-1.0.3-py2.py3-none-any.whl
Collecting tinytimer<1.0.0,>=0.0.0 (from pyensembl)
  Using cached tinytimer-0.0.0-py3-none-any.whl
Collecting gtfparse<3.0.0,>=2.5.0 (from pyensembl)
  Using cached gtfparse-2.5.0-py3-none-any.whl.metadata (2.1 kB)
Collecting serializable<1.0.0,>=0.2.1 (from pyensembl)
  Using cached serializable-0.4.1-py3-none-any.whl.metadata (2.2 kB)
Collecting pylint<3.0.0,>=2.17.2 (from pyensembl)
  Using cached pylint-2.17.7-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas>=0.15.2 in /opt/conda/lib/python3.13/site-packages (from datacache<2.0.0,>=1.4.0->pyensembl) (2.3.2)
Collecting appdirs>=1.4.0 (from datacache<2.0.0,>=1.4.0->pyensembl)
  Using cached appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting progressbar33>=2.4 (from datacache<2.0.0,>=1.4.0->pyensembl)
  Using cached progressbar33-2.4-py3-none-any.whl
Requirement already satisfied: requests>=2.5.1 in /opt/conda/lib/python3.13/site-packages (from datacache<2.0.0,>=1.4.0->pyensembl) (2.32.5)
Collecting mock (from datacache<2.0.0,>=1.4.0->pyensembl)
  Using cached mock-5.2.0-py3-none-any.whl.metadata (3.1 kB)
Collecting polars<0.21.0,>=0.20.2 (from gtfparse<3.0.0,>=2.5.0->pyensembl)
  Using cached polars-0.20.31-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting pyarrow<14.1.0,>=14.0.2 (from gtfparse<3.0.0,>=2.5.0->pyensembl)
  Using cached pyarrow-14.0.2.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.13/site-packages (from pyarrow<14.1.0,>=14.0.2->gtfparse<3.0.0,>=2.5.0->pyensembl) (2.2.6)
Requirement already satisfied: platformdirs>=2.2.0 in /opt/conda/lib/python3.13/site-packages (from pylint<3.0.0,>=2.17.2->pyensembl) (4.4.0)
Collecting astroid<=2.17.0-dev0,>=2.15.8 (from pylint<3.0.0,>=2.17.2->pyensembl)
  Using cached astroid-2.15.8-py3-none-any.whl.metadata (4.7 kB)
Collecting isort<6,>=4.2.5 (from pylint<3.0.0,>=2.17.2->pyensembl)
  Using cached isort-5.13.2-py3-none-any.whl.metadata (12 kB)
Collecting mccabe<0.8,>=0.6 (from pylint<3.0.0,>=2.17.2->pyensembl)
  Using cached mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting tomlkit>=0.10.1 (from pylint<3.0.0,>=2.17.2->pyensembl)
  Using cached tomlkit-0.13.3-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: dill>=0.3.6 in /opt/conda/lib/python3.13/site-packages (from pylint<3.0.0,>=2.17.2->pyensembl) (0.4.0)
Collecting lazy-object-proxy>=1.4.0 (from astroid<=2.17.0-dev0,>=2.15.8->pylint<3.0.0,>=2.17.2->pyensembl)
  Using cached lazy_object_proxy-1.12.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (5.1 kB)
Collecting wrapt<2,>=1.14 (from astroid<=2.17.0-dev0,>=2.15.8->pylint<3.0.0,>=2.17.2->pyensembl)
  Using cached wrapt-1.17.3-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.4 kB)
Collecting simplejson (from serializable<1.0.0,>=0.2.1->pyensembl)
  Using cached simplejson-3.20.2-cp313-cp313-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.13/site-packages (from pandas>=0.15.2->datacache<2.0.0,>=1.4.0->pyensembl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.13/site-packages (from pandas>=0.15.2->datacache<2.0.0,>=1.4.0->pyensembl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.13/site-packages (from pandas>=0.15.2->datacache<2.0.0,>=1.4.0->pyensembl) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=0.15.2->datacache<2.0.0,>=1.4.0->pyensembl) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.13/site-packages (from requests>=2.5.1->datacache<2.0.0,>=1.4.0->pyensembl) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.13/site-packages (from requests>=2.5.1->datacache<2.0.0,>=1.4.0->pyensembl) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.13/site-packages (from requests>=2.5.1->datacache<2.0.0,>=1.4.0->pyensembl) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.13/site-packages (from requests>=2.5.1->datacache<2.0.0,>=1.4.0->pyensembl) (2025.8.3)
Using cached pyensembl-2.3.13-py3-none-any.whl (55 kB)
Using cached datacache-1.4.1-py3-none-any.whl (20 kB)
Using cached gtfparse-2.5.0-py3-none-any.whl (15 kB)
Using cached polars-0.20.31-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28.8 MB)
Using cached pylint-2.17.7-py3-none-any.whl (537 kB)
Using cached astroid-2.15.8-py3-none-any.whl (278 kB)
Using cached isort-5.13.2-py3-none-any.whl (92 kB)
Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Using cached serializable-0.4.1-py3-none-any.whl (12 kB)
Using cached wrapt-1.17.3-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (88 kB)
Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Using cached lazy_object_proxy-1.12.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (71 kB)
Using cached tomlkit-0.13.3-py3-none-any.whl (38 kB)
Using cached mock-5.2.0-py3-none-any.whl (31 kB)
Using cached simplejson-3.20.2-cp313-cp313-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (152 kB)
Building wheels for collected packages: pyarrow
  Building wheel for pyarrow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyarrow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [358 lines of output]
      <string>:34: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
      /tmp/pip-build-env-9wnbo9n5/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      /tmp/pip-build-env-9wnbo9n5/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      /tmp/pip-build-env-9wnbo9n5/overlay/lib/python3.13/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: Apache Software License

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      /tmp/pip-build-env-9wnbo9n5/overlay/lib/python3.13/site-packages/setuptools/dist.py:483: SetuptoolsDeprecationWarning: Pattern '../LICENSE.txt' cannot contain '..'
      !!

              ********************************************************************************
              Please ensure the files specified are contained by the root
              of the Python package (normally marked by `pyproject.toml`).

              By 2026-Mar-20, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://packaging.python.org/en/latest/specifications/glob-patterns/ for details.
              ********************************************************************************

      !!
        for path in sorted(cls._find_pattern(pattern, enforce_match))
      /tmp/pip-build-env-9wnbo9n5/overlay/lib/python3.13/site-packages/setuptools/dist.py:483: SetuptoolsDeprecationWarning: Cannot find any files for the given pattern.
      !!

              ********************************************************************************
              Pattern '../LICENSE.txt' did not match any files.

              By 2026-Mar-20, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************

      !!
        for path in sorted(cls._find_pattern(pattern, enforce_match))
      /tmp/pip-build-env-9wnbo9n5/overlay/lib/python3.13/site-packages/setuptools/dist.py:483: SetuptoolsDeprecationWarning: Pattern '../NOTICE.txt' cannot contain '..'
      !!

              ********************************************************************************
              Please ensure the files specified are contained by the root
              of the Python package (normally marked by `pyproject.toml`).

              By 2026-Mar-20, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://packaging.python.org/en/latest/specifications/glob-patterns/ for details.
              ********************************************************************************

      !!
        for path in sorted(cls._find_pattern(pattern, enforce_match))
      /tmp/pip-build-env-9wnbo9n5/overlay/lib/python3.13/site-packages/setuptools/dist.py:483: SetuptoolsDeprecationWarning: Cannot find any files for the given pattern.
      !!

              ********************************************************************************
              Pattern '../NOTICE.txt' did not match any files.

              By 2026-Mar-20, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************

      !!
        for path in sorted(cls._find_pattern(pattern, enforce_match))
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/conftest.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/substrait.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/fs.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/acero.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/util.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/_generated_version.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/filesystem.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/jvm.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/cuda.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/types.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/compute.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/json.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/feather.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/hdfs.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/pandas_compat.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/benchmark.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/csv.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/dataset.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/flight.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/__init__.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/_compute_docstrings.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/ipc.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/cffi.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      copying pyarrow/orc.py -> build/lib.linux-x86_64-cpython-313/pyarrow
      creating build/lib.linux-x86_64-cpython-313/pyarrow/interchange
      copying pyarrow/interchange/from_dataframe.py -> build/lib.linux-x86_64-cpython-313/pyarrow/interchange
      copying pyarrow/interchange/column.py -> build/lib.linux-x86_64-cpython-313/pyarrow/interchange
      copying pyarrow/interchange/__init__.py -> build/lib.linux-x86_64-cpython-313/pyarrow/interchange
      copying pyarrow/interchange/dataframe.py -> build/lib.linux-x86_64-cpython-313/pyarrow/interchange
      copying pyarrow/interchange/buffer.py -> build/lib.linux-x86_64-cpython-313/pyarrow/interchange
      creating build/lib.linux-x86_64-cpython-313/pyarrow/parquet
      copying pyarrow/parquet/encryption.py -> build/lib.linux-x86_64-cpython-313/pyarrow/parquet
      copying pyarrow/parquet/core.py -> build/lib.linux-x86_64-cpython-313/pyarrow/parquet
      copying pyarrow/parquet/__init__.py -> build/lib.linux-x86_64-cpython-313/pyarrow/parquet
      creating build/lib.linux-x86_64-cpython-313/pyarrow/vendored
      copying pyarrow/vendored/docscrape.py -> build/lib.linux-x86_64-cpython-313/pyarrow/vendored
      copying pyarrow/vendored/version.py -> build/lib.linux-x86_64-cpython-313/pyarrow/vendored
      copying pyarrow/vendored/__init__.py -> build/lib.linux-x86_64-cpython-313/pyarrow/vendored
      creating build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_pandas.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_cffi.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_gdb.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_cuda_numba_interop.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_array.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_schema.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_util.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/conftest.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/pandas_threaded_import.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_substrait.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/util.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_orc.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_udf.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_cuda.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_misc.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_jvm.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_cpp_internals.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_acero.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_feather.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_hdfs.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/arrow_16597.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_deprecations.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/arrow_7980.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_flight_async.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_ipc.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_strategies.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_csv.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_exec_plan.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_memory.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_json.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_tensor.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_cython.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/__init__.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_dataset_encryption.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_convert_builtin.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_compute.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_io.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_flight.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_builder.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_filesystem.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_sparse_tensor.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/strategies.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_types.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/pandas_examples.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_gandiva.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_dataset.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_extension_type.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_adhoc_memory_leak.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/read_record_batch.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_fs.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_table.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      copying pyarrow/tests/test_scalars.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests
      creating build/lib.linux-x86_64-cpython-313/pyarrow/tests/interchange
      copying pyarrow/tests/interchange/test_interchange_spec.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests/interchange
      copying pyarrow/tests/interchange/test_conversion.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests/interchange
      copying pyarrow/tests/interchange/__init__.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests/interchange
      creating build/lib.linux-x86_64-cpython-313/pyarrow/tests/parquet
      copying pyarrow/tests/parquet/test_pandas.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests/parquet
      copying pyarrow/tests/parquet/conftest.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests/parquet
      copying pyarrow/tests/parquet/encryption.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests/parquet
      copying pyarrow/tests/parquet/test_encryption.py -> build/lib.linux-x86_64-cpython-313/pyarrow/tests/parquet

In [26]:
from pyensembl import EnsemblRelease

ensembl = EnsemblRelease(105)  # GRCh38
def annotate(chrom, pos):
    genes = ensembl.genes_at_locus(contig=chrom, position=pos)
    return ", ".join(g.gene_name for g in genes) if genes else None

df['gene'] = df.apply(lambda x: annotate(x['CHROM'], x['POS']), axis=1)

ModuleNotFoundError: No module named 'pyensembl'

➡️ Then add effect info from VEP’s REST API:

In [ ]:
import requests
def vep_annot(chrom, pos, ref, alt):
    url = f"https://rest.ensembl.org/vep/human/region/{chrom}:{pos}/{ref}/{alt}?"
    r = requests.get(url, headers={"Content-Type": "application/json"})
    if r.ok:
        data = r.json()[0]
        return data.get("most_severe_consequence")
    return None

df['effect'] = df.apply(lambda x: vep_annot(x['CHROM'], x['POS'], x['REF'], x['ALT']), axis=1)